syntax = "proto3";

package uk.co.fivium.grpc.gis;

import "enums/LineNavigationType.proto";
import "enums/CoordinateSystem.proto";
import "splitPolygon/SplitPolygonRequest.proto";
import "splitPolygon/SplitPolygonResponse.proto";
import "buildPolygon/BuildPolygonRequest.proto";
import "buildPolygon/BuildPolygonResponse.proto";

import "migration/blockandsubarea/MigrateBlockOrSubAreaRequest.proto";
import "migration/blockandsubarea/MigrateBlockOrSubAreaResponse.proto";
import "migration/blockandsubarea/BlockAndSubareaValidationRequest.proto";
import "migration/blockandsubarea/ValidationResponse.proto";
import "migration/blockandsubarea/TopologicallyEqualValidationRequest.proto";

option java_multiple_files = true;
option java_outer_classname = "ArcGisServiceProto";

service ArcGisService {
  rpc splitPolygon (SplitPolygonRequest) returns (SplitPolygonResponse) {};
  rpc buildPolygon (BuildPolygonRequest) returns (BuildPolygonResponse) {};
  rpc migrateBlockOrSubarea (MigrateBlockOrSubAreaRequest) returns (MigrateBlockOrSubAreaResponse) {};
  rpc validateBlockAndSubarea (BlockAndSubareaValidationRequest) returns (ValidationResponse) {};
  rpc validateTopologicallyEqual (TopologicallyEqualValidationRequest) returns (ValidationResponse) {};
}