package uk.co.nstauthority.licensingmanagementservice.validation;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import org.springframework.validation.BeanPropertyBindingResult;
import org.springframework.validation.BindingResult;
import org.springframework.validation.Errors;
import org.springframework.validation.FieldError;

public class ValidatorTestingUtil {

  public static final String STRING_300_CHARACTERS =
      "01234567890123456789012345678901234567890123456789" +
      "01234567890123456789012345678901234567890123456789" +
      "01234567890123456789012345678901234567890123456789" +
      "01234567890123456789012345678901234567890123456789" +
      "01234567890123456789012345678901234567890123456789" +
      "01234567890123456789012345678901234567890123456789";

  public static final String STRING_301_CHARACTERS = STRING_300_CHARACTERS + "0";

  private ValidatorTestingUtil() {
    throw new IllegalStateException("ValidatorTestingUtil is a util class and should not be instantiated");
  }

  /**
   * Produces a map of error pairs generated by the validation process in case one or more
   * field values of the form under test are rejected. The error pair consists of the formField linked to the error
   * and the corresponding errorMessage
   * @param errors stores validation errors for a specific form under test
   * @return the list of error messages found when a form is being validated
   */
  public static Map<String, List<String>> getErrorsFieldsAndMessages(Errors errors){
    return errors.getAllErrors().stream()
        .filter(FieldError.class::isInstance)
        .map(FieldError.class::cast)
        .collect(
            Collectors.groupingBy(FieldError::getField, Collectors.mapping(FieldError::getDefaultMessage, Collectors.toList())));
  }

  // Below methods extractErrors and extractErrorMessages copied from WIOS in the teams copy

  /**
   * Return a map of field id -> set of field error codes for a BindingResult.
   */
  public static Map<String, Set<String>> extractErrors(BindingResult bindingResult) {

    return bindingResult.getFieldErrors().stream()
        .collect(Collectors.groupingBy(
            FieldError::getField,
            LinkedHashMap::new,
            Collectors.mapping(FieldError::getCode, Collectors.toSet())
        ));

  }

  public static Map<String, Set<String>> extractErrorMessages(BindingResult bindingResult) {

    return bindingResult.getFieldErrors().stream()
        .collect(Collectors.groupingBy(
            FieldError::getField,
            LinkedHashMap::new,
            Collectors.mapping(FieldError::getDefaultMessage, Collectors.toSet())
        ));

  }

  public static BindingResult getBindingResult(Object form, String objectName) {
    return new BeanPropertyBindingResult(form, objectName);
  }

  public static BindingResult getBindingResult(Object form) {
    return getBindingResult(form, "form");
  }

}
