kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        # We can only mount volume caches into the working directory, so all steps which use Gradle must have
        # the GRADLE_USER_HOME environment variable pointing here.
        - ./gradle_cache

  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      - echo "$${BITBUCKET_SSH_KEY}" > bitbucket_ssh_key
      - chmod 600 bitbucket_ssh_key
      - export GIT_SSH_COMMAND="ssh -i bitbucket_ssh_key -F /dev/null  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      - git submodule update --init --recursive
    environment:
      BITBUCKET_SSH_KEY:
        from_secret: bitbucket_ssh_key

  - name: build-frontend
    image: node:18
    commands:
      - cd fivium-design-system-core && npm install && npx gulp buildAll && cd ..
      - npm install && npx gulp buildAll

  - name: build-backend
    image: quay.io/testcontainers/dind-drone-plugin
    privileged: true
    environment:
      TZ: Europe/London
      CI_WORKSPACE: /drone/src
      GRADLE_USER_HOME: /drone/src/gradle_cache
      DOCKER_CONFIG_JSON:
        from_secret: docker_config
      DOCKER_CONFIG: /drone/dockerconfig
    volumes:
      - name: docker-cache-overlay2
        path: /drone/docker/overlay2
      - name: docker-cache-image
        path: /drone/docker/image
    settings:
      storage_driver: overlay2 --insecure-registry repo1.dev.fivium.local:5000 --dns=192.168.10.1
      cmd:
        - mkdir /drone/dockerconfig
        - echo $DOCKER_CONFIG_JSON > /drone/dockerconfig/config.json
        - chmod +x gradlew
        - ./gradlew checkstyleMain test bootJar --continue --parallel --max-workers=3
      build_image: repo1.dev.fivium.local:5000/docker-compose-java21

  - name: sync-reports
    image: alpine:3.16.0
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./gradle_cache

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: digital-spring-boot-template-project-builds
      template: "*{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>\nReports published to: http://drone-assets.fivium.local:9090/digital-springboot-template-project/{{build.number}}/"
    when:
      status: [ success, failure ]
trigger:
  event:
    include:
      - push

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/digital-springboot-template-project

  - name: drone-cache
    host:
      path: /home/fivium/drone-cache

  - name: docker-cache-overlay2
    host:
      path: /home/fivium/docker-drone-cache-v2/overlay2

  - name: docker-cache-image
    host:
      path: /home/fivium/docker-drone-cache-v2/image

---
kind: pipeline
type: docker
name: github-pr

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git:v2.26.2
    commands:
      # Manually cloning as there seems to be a bug with DRONE_BRANCH on Pull Request Events
      # DRONE_BRANCH is set to the target branch, rather than the current branch
      # This means that Sonarcloud doesn't think anything has changed
      - git clone https://github.com/Fivium/digital-springboot-template.git .
      - git checkout $DRONE_SOURCE_BRANCH

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        # We can only mount volume caches into the working directory, so all steps which use Gradle must have
        # the GRADLE_USER_HOME environment variable pointing here.
        - ./gradle_cache
        - ./sonar_cache

  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      - echo "$${BITBUCKET_SSH_KEY}" > bitbucket_ssh_key
      - chmod 600 bitbucket_ssh_key
      - export GIT_SSH_COMMAND="ssh -i bitbucket_ssh_key -F /dev/null  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      - git submodule update --init --recursive
    environment:
      BITBUCKET_SSH_KEY:
        from_secret: bitbucket_ssh_key

  - name: build-frontend
    image: node:18
    commands:
      - cd fivium-design-system-core && npm install && npx gulp buildAll && cd ..
      - npm install && npx gulp buildAll

  # This is in the PR pipeline so the code-analysis below can access the test data (to see coverage)
  - name: build-backend
    image: quay.io/testcontainers/dind-drone-plugin
    privileged: true
    # See https://confluence.fivium.co.uk/display/JAVA/Testcontainers
    environment:
      TZ: Europe/London
      CI_WORKSPACE: /drone/src
      GRADLE_USER_HOME: /drone/src/gradle_cache
      DOCKER_CONFIG_JSON:
        from_secret: docker_config
      DOCKER_CONFIG: /drone/dockerconfig # testcontainers override location for Docker config JSON
    volumes:
      - name: docker-cache-overlay2
        path: /drone/docker/overlay2
      - name: docker-cache-image
        path: /drone/docker/image
    settings:
      storage_driver: overlay2 --insecure-registry repo1.dev.fivium.local:5000 --dns=192.168.10.1
      cmd:
        - mkdir /drone/dockerconfig
        - echo $DOCKER_CONFIG_JSON > /drone/dockerconfig/config.json
        - chmod +x gradlew
        - ./gradlew checkstyleMain test bootJar --continue --parallel --max-workers=3
      build_image: repo1.dev.fivium.local:5000/docker-compose-java21

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./gradle_cache
#        - ./sonar_cache

trigger:
  event:
    - pull_request

volumes:
  - name: drone-cache
    host:
      path: /home/fivium/drone-cache

  - name: docker-cache-overlay2
    host:
      path: /home/fivium/docker-drone-cache-v2/overlay2

  - name: docker-cache-image
    host:
      path: /home/fivium/docker-drone-cache-v2/image
---

kind: secret
name: docker_config
data: Abo367lNHSaLTE5xJNl5H6tWMdYJCKRKcxw0OXvrj35I0cPW2dFX3mUTKYoQifNtJNt5l8Mvi9nlVsvp3Q0bm41ZbX7Ue79yPaLj5At55+81/+TZZ3i9EUytGd4ONvhl+BHgU5J0F6yHkiEHWsgyddHCzg3FMn8JEML/k+TQpDe7ki1ZA19moIHS+UC5KCqUBhGBhu0lMHHjGSu4Dmo0vkF3FPl/1ke6TVPD39Y/4n+Xrz6JWE5eqDtT3ylNtFG118eFQwmpvH8lKjLUV/k1yzdYnCIKBSVoIHs5qNbQ7dcLxIkDnQoha6RXy8cG6R/xst7JOOEbCOoC+dKGZMXvxmr/VY8FGsNyM7n5kb8y

---

kind: secret
name: bitbucket_ssh_key
data: KWcDkbhbhAR09d5xKMycV82e+7IVoxl47qtD4ZQ6LL2t4RW1mmCUOWsO9SufI1BkvwiA1qvYdZsz/uFhlOO9nW8QB8w765HE8QOb/B0rA2VUF1eY7C7shyNFwbE7Lhv2dHty2Lpum/diPC16lr3AECClaidb7z/rDRawKubie0GRoTVmoANBjEaLSD9/s7bNMC54X7eNIisG3lfKR0cdhlfuOPbuNCtZUuMAAYkWSQZiJsuH2IIrnfagJHd4rxY0vcREBAa2clca5J9dkxX6oGmKCRrhZ80TE1M2Qf41c0zqGCYc+7DIQXN/tePTal6mZ920tpwF4LE2u9zkEcD3iVUPDLVsmx0pXUvwyFhQgrp4yHtC2N/VWdRKIrqfaPhguslMlUvzQ2B9DFOKoAMBsSwltVGdxdZPpBDnjURpfxTjD3wnEc5Pm7atFnTB6Xh2KiDTln2D41ny5Xyk/MlD2Gi5B0kKXd0A9NyiT6QHCxzCLOzLQHUU2VeddENw5w0CumtOWjMDRmTKY3FLRpIISAQobjcQSWZfPjdGAd6vKHahU0/bM4s2iw+8UxXgp+MiwnLYa3lDfw+9ZfAOegW30s2lJAt5eKMFuCl8KIPw3uv4UCDwb2aIj+UYdTrHBEtg8AmRoBe+X8UVGnkOlQTZsvo/aiBLBGn53WqZ8MfDoTio5pTK+31Dc/OlP+vWn825gOEMMLEoO5zWNTp9Kk8CMTTYXyBepSAS2kzM1yg2But708//Fsuw1nmDwYEng3gwY+ICnCFpAEei/1gMNynoJNo5jHF4RopsVd5twzMmQK0SUoSB7SB0F98lPiFd1qwKLbuiq0s4pWLUvZI8WEuLhmr4guwql4lxA1KrhMHaiVrQjiix+3gYaAHylODWTwl8i6kcuHuEW49/+fwUVy2zgP8pHMaAHZ9iB92QvCdAJzKSo/StRme+MnV8+rGJbPUjF4bfeCAJzUwg9S1RaukVkfoRlhyRnCz5H5v5yFbWHWz4mb9S0M9+WMpxwJ9oyO+WOVMYre96QSK1CNe+wIk7vdSuQsF8Xz1fk480DvD8mLsLcqqUJ0uy23qT6AULmbRcPg6uA2pnxRHxUFbuABYqSWUErQ+fHyPgrEAV0oOFZq+g0I4DNDEU0XUM4iCoDy9tcSDJx4iLCIzoTJApPLCXQ00UYojvvuB8dSTacjuW1xWyjElEat7NygY+IY9lxzi3F0wQwaegbQbxU7c5JoNPWE3N5+T7t68havjv1/79hJJ9h3X9W6yaq1W46zooPbxHOjDa87MS+ldLH5uttFlX/7omi1qO3DklBAzLVSMG2F9F/3CEnogScCw0DP/UiAU5Wfaz8cyyt0w6JUzhUFPF5UU17u+6nFUW2op6A5rgP3ZrWNKSBtj+dj3ku6uId4xcqEF60HPzBsMwOe8WJzJgf+ZmtEuFjnQ+XrDfvZMA3R4Z27G5OQwrTmQwcQaHhcJheyZNPtzZ31t5EZc1Zc6BKpeSwJEpvq0u2boaBkK09zuJfnHVdHYPa8lRGRS/WkMUheoY2oHcu2u/a0Lb8zC0TfcHWPN6UU69ufLUNjNi8w29nWnbS5Pc1tIdU3FTUecy/oCub4ZNemnT1Hq8fv2Wm2F3pUGv79aQ6MRwsF5y644T6eQr5EZJ5JUjzDYYg4eK2MR/3NUmLI8mka8a4giN9jJ1pHozilscNn7xCkt5wqQoSZXBYzUaCmjOi+y1o8ncuy7K5mj5rxpGHuHaAwkEpy+uNu4jieaUZLGswaFHpbaz3CGJEZeNSpbKIr0sckeJsZWpoF6NtvtDk54Z6OxbAYj2TdwD3kw0G/ghMUXe14LvdH5i/PvWbx5HVUZw34h/BDs0ENmcjO5DYVqbTZ10h1cXCpg2l4qmmGesPB7s97VI2yS8fmXqAWg2XFTulT77NdMUgzGuSaHDcqe4Ok3xEDSa9hwT6M5FFz0Q9JKRFCoOzCsxpr7HmXjA5XQiKDILk/2g7qpyZHUs/VERxHQPsjkd92RZTAYfZwcUgUGRoHLczNLfxSInv90OV08xz9xijVNvyvocPHpEoKW4HuAD39K3ge4y+cvkUqQI3O/Qs/PnWqbeMpNqPbIA07GkrIehGdgdn7slTsA40tXtnKkHKLptgX9Pmu5EWKca8Hq3xp3ng6DGWCbYBkbJPiRPgNTGP9dggCHEu/aThdYyXtOkqVV0ibrxl4+rE3LBOUu0PLp5xRO5e+FAKB3IODjg0qpWVIL02Uj3cYWSMxt7M4FjNW2SQnyK4xl8z4Hc1njteCAV2F1nheyEovw3KRDUiAJ2auEghhv3I8LsO5zcpviQhxpd4qcY2sfxxdaLkRml7KVniqg0Ogkmkxg/yZhrDZp54UzaganesjTzUwuk5jsmdEE8VKV7lBxdy7m27jubSagbuwolPevfaJwoxEL8tGCsdInm6Z2EVTyCqXpTLjS6E6Xoxl2bZA+E9zdoSZc7qcGpEkLUhVbQfc64yD02wHPqbCEcvrkd51R/0j9KBnLbxotsVm1HGjyQyqzW8u/ulD0P5PkkFmqACnvzG7eORPevJeHxr3M1OxtkBmrRU8LiTTpuAuyfR/Bad0XnkizCe5+YP4X83uI52JjlODvLMOxVNxLWR0jykEO6TShdk15LBH0Jh9NQ64FwAjN5RFk+wI6CH7Z7gaFg6M0J/biJJMpjP5rtUorZuchMd5Hlu+DMEb61ATfAzKeuLLITE7uG6CyXfwDsUo/08sSphjvH+oLYDwwPUEyB7q2jaUTwr/XlfL+AAyOqaaLirvLRE2PeXgi/z/2Si5nNaFxCqB2IDPWYRYNTl6jg8oc/E6QPuSUcBmCxEP1qckXgoMVxcjuPFjCRJ1VbPXuM1mRjrcL8rQoWx/jPtemGDmE8i9g9MYhkj1O/cm2om+o/H/Q+TfTdzETYoHEiXhIfTbvdHzcZn4KcsEW8GHunO1g117dCcjIZ/4G1p/XH6+3Ah/ssVuPVenjxITr+Fym0urZedu7OsDJrtQ6ADzrhXRV0O9DB+XNiaqEOm0IZa5qvtSYm7cnWbhYPlbMg9LiNebiCfh2JYoN9rcMDthDDeXKByziPX/1ltHnDRq0H1UMz+jtRlsJLJosT7y5BtqG5V9pYTbSMzJz9VYh9gY50Q9jfMAaO1RIjpWbwvnjsOMwHOJfpn+aWN3MyjILEBL9OCIbIjyxlyIBNKQKyVJ0JbdoJkKbCypmMwQCVljuoxr2oL1Vs8R6CCasr8k19VBDzd8uS5cPkhHhxIsN5YJa8L/OwzznIHNvj3EvWA+tnQ4+TnNVseKTa7N4R4ORc7IbiQPQMBVKRMA46NqWMTMeZsr7oHQ9EQdaVNcGry4mscVWcf2H0q0+ltlH1GwipAokFwHFkzV7zPBU7B5wCjthIMbc8s8msxNEUxbHnqpYRN8h7wfC0qMnco6GFeAtlJvl6MKnrOKA7VXFPg5QbZRDIzgcZRvdmKqRnE7iHQJP+izqibMEMVvkSnnPBic74P9c=
