server.error.path=/error
server.error.whitelabel.enabled=false
server.servlet.context-path=${XYZ_CONTEXT_PATH:/xyz}

# Service branding
branding.service.name=XYZ
branding.service.mnemonic=XYZ
branding.service.support-contact.email=example@xyz.com
branding.service.support-contact.phone=xyz123

branding.customer.name=North Sea Transition Authority
branding.customer.mnemonic=NSTA

# Freemarker
spring.freemarker.settings.output_format=HTMLOutputFormat
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.suffix=.ftl

# Datasource
spring.datasource.url=${database.url}
spring.datasource.username=xyz_app
spring.datasource.password=${schema.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=xyz

# Don't allow queries to be executed in views or entities to be automatically flushed outside of an explicit transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.schemas=xyz

saml.registration-id=saml

#Spring Session properties
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=${spring.jpa.properties.hibernate.default_schema}.SPRING_SESSION
server.servlet.session.timeout=180m

logging.pattern.correlation=[%X{CORRELATION_ID}]

service.error.includeStacktrace=false

# TODO XYZ - check extensions
file-upload.default-permitted-file-extensions=bmp, csv, doc, docx, jpeg, jpg, pdf, png, txt, xls, xlsx
file-upload.default-maximum-file-size=50MB
spring.servlet.multipart.max-file-size=${file-upload.default-maximum-file-size}
spring.servlet.multipart.max-request-size=${spring.servlet.multipart.max-file-size}

# Feedback management service
fms.url-base=${XYZ_FMS_URL_BASE}
fms.connectionTimeoutSeconds=${XYZ_FMS_CONNECTION_TIMEOUT_SECONDS:20}
fms.saveFeedbackUrl=${XYZ_FMS_SUBMIT_ENDPOINT:/api/v1/save-feedback}
fms.service-name=XYZ
fms.presharedKey=${XYZ_FMS_PRESHARED_KEY}
