database.url=jdbc:postgresql://${LMS_DATABASE_URL}
schema.password=${LMS_DATABASE_PASSWORD}
spring.flyway.placeholders.datawarehouse-user-password=${LMS_DATAWAREHOUSE_USER_PASSWORD}

spring.flyway.out-of-order=${LMS_ENABLE_FLYWAY_OUT_OF_ORDER:false}

energy-portal.logout-url=${EPAS_LOGOUT_REQUEST_URL}
energy-portal.logout-pre-shared-key=${LMS_ENERGY_PORTAL_LOGOUT_KEY}
energy-portal.registration-url=${LMS_ENERGY_PORTAL_REGISTRATION_URL}

energy-portal-api.url=${LMS_ENERGY_PORTAL_API_URL}
energy-portal-api.preSharedKey=${LMS_ENERGY_PORTAL_API_TOKEN}

file-upload.s3.default-bucket=${LMS_S3_DEFAULT_BUCKET}
file-upload.s3.region=${LMS_S3_SIGNING_REGION:eu-west-2}
file-upload.clamav.host=${LMS_CLAMAV_HOST}
file-upload.clamav.port=${LMS_CLAMAV_PORT}
file-upload.clamav.timeout=PT1M

# TODO get gov uk pay key
#digital-payments-library.govukpay.api-key=${LMS_GOV_PAY_API_KEY}

# Error properties
service.error.include-stacktrace=${LMS_ENABLE_STACK_TRACE:false}

#Analytics
analytics.serviceAnalyticIdentifier=${LMS_ANALYTICS_SERVICE_IDENTIFIER:}
analytics.energyPortalAnalyticIdentifier=${LMS_ANALYTICS_ENERGY_PORTAL_IDENTIFIER:}

# Notify
digital-notification-library.mode=${LMS_NOTIFY_MODE}

# FTSS
ftss.base-url=${LMS_FTSS_BASE_URL:}
ftss.api-key=${LMS_FTSS_API_KEY:}

# Actuator
actuator.api-key=${LMS_ACTUATOR_API_KEY:}