server.error.path=/error
server.error.whitelabel.enabled=false
server.servlet.context-path=${LMS_CONTEXT_PATH:/lms}

# Service branding
branding.service.name=Licence Management Service
branding.service.mnemonic=LMS
branding.service.support-contact.email=example@xyz.com
branding.service.support-contact.phone=xyz123

branding.customer.name=North Sea Transition Authority
branding.customer.mnemonic=NSTA
branding.customer.privacy-policy-url=https://www.nstauthority.co.uk/footer/privacy-statement/

# Freemarker
spring.freemarker.settings.output_format=HTMLOutputFormat
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.suffix=.ftl

spring.flyway.validate-on-migrate=false
# Datasource
spring.datasource.url=${database.url}
spring.datasource.username=lms_app
spring.datasource.password=${schema.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=lms

# Don't allow queries to be executed in views or entities to be automatically flushed outside of an explicit transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.schemas=lms
spring.flyway.placeholders.application-schema=${spring.flyway.schemas}

# SAML
saml.registration-id=saml
saml.entity-id=${EPAS_SAML_ENTITY_ID:}
saml.login-url=${EPAS_SAML_LOGIN_URL:}
saml.consumer-service-location=${EPAS_SAML_BASE_URL:}${server.servlet.context-path}/login/saml2/sso/saml
saml.certificate=${LMS_SAML_CERTIFICATE:}

#Spring Session properties
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=${spring.jpa.properties.hibernate.default_schema}.SPRING_SESSION
server.servlet.session.timeout=180m

logging.pattern.correlation=[%X{CORRELATION_ID}] 

service.error.includeStacktrace=false

file-upload.default-permitted-file-extensions=bmp, csv, doc, docx, jpeg, jpg, pdf, png, txt, xls, xlsx
file-upload.default-maximum-file-size=50MB
spring.servlet.multipart.max-file-size=${file-upload.default-maximum-file-size}
spring.servlet.multipart.max-request-size=${spring.servlet.multipart.max-file-size}

# Feedback management service
fms.url-base=${LMS_FMS_URL_BASE}
fms.connectionTimeoutSeconds=${LMS_FMS_CONNECTION_TIMEOUT_SECONDS:20}
fms.saveFeedbackUrl=${LMS_FMS_SUBMIT_ENDPOINT:/api/v1/save-feedback}
fms.service-name=LMS
fms.presharedKey=${LMS_FMS_PRESHARED_KEY}

# Monitoring
management.statsd.metrics.export.enabled=${LMS_ENABLE_STATSD:false}
management.statsd.metrics.export.host=${LMS_STATSD_HOST:}
management.statsd.metrics.export.port=${LMS_STATSD_PORT:}
management.statsd.metrics.export.flavor=DATADOG
management.metrics.tags.instance=${LMS_METRICS_INSTANCE_TAG:}
management.metrics.tags.source-type=${LMS_METRICS_ENVIRONMENT_NAME:}
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health

# Scheduling
spring.task.scheduling.pool.size=10

# Energy Portal Message Queue
epmq.sns-sqs.aws-access-key-id=${LMS_EPMQ_SNS_SQS_AWS_ACCESS_KEY_ID:}
epmq.sns-sqs.aws-secret-access-key=${LMS_EPMQ_SNS_SQS_AWS_SECRET_ACCESS_KEY:}
epmq.sns-sqs.aws-region-id=${LMS_EPMQ_SNS_SQS_AWS_REGION_ID:eu-west-2}
epmq.environment-suffix=${LMS_EPMQ_ENVIRONMENT_SUFFIX:}

# Energy Portal Accounts Service
energy-portal-accounts.service-name=lms
energy-portal-accounts.preshared-key=${EPAS_SPRING_BOOT_STARTER_PRESHARED_KEY:}
# todo EPUO-677: remove, and replace with dev properties once domain checks are added to this service
well-known-organisation-groups.groups=

# Notify
digital-notification-library.govuk-notify.api-key=${LMS_NOTIFY_API_KEY}
digital-notification-library.test-mode.email-recipients=${LMS_NOTIFY_TEST_EMAIL:}
digital-notification-library.test-mode.sms-recipients=0123456789

# Digital signature
# Do not change these fields without also updating the GlobalSign identity. They must match exactly.
digital-signature.organisation=Oil and Gas Authority
digital-signature.email=ukop@nstauthority.co.uk
digital-signature.state=Aberdeenshire
digital-signature.country=GB
digital-signature.locality=Aberdeen
digital-signature.reason=On behalf of the Secretary of State
digital-signature.location=North Sea Transition Authority

digital-signature.common-name=${digital-signature.organisation}
digital-signature.line-1=Digitally signed by and on behalf of the ${digital-signature.organisation}
digital-signature.line-3=${digital-signature.organisation}
spring.config.import=classpath:config/well-known-organisation-groups.yaml
