-- LMS1-644: drop team_roles for Role values removed by the offshore/carbon storage role consolidation.
-- Run against local-dev, shared-dev, ST before the new Role code deploys - Role.valueOf() throws on these otherwise.
-- Safe to re-run.

DELETE FROM lms.team_roles
WHERE role IN (
  'CASE_MANAGER_NEW_VENTURES',
  'CASE_MANAGER_OPERATIONS',
  'STEWARD_NEW_VENTURES',
  'STEWARD_OPERATIONS',
  'DECISION_ISSUER_NEW_VENTURES',
  'DECISION_ISSUER_OPERATIONS',
  'CONTINUATION_REVIEWER_NEW_VENTURES',
  'CONTINUATION_REVIEWER_OPERATIONS',
  'CASE_MANAGER_CS_NEW_VENTURES',
  'CASE_MANAGER_CS_CTS',
  'STEWARD_CS_NEW_VENTURES',
  'STEWARD_CS_CTS',
  'DECISION_ISSUER_CS_NEW_VENTURES',
  'DECISION_ISSUER_CS_CTS'
);

DELETE FROM lms.team_roles_aud
WHERE role IN (
  'CASE_MANAGER_NEW_VENTURES',
  'CASE_MANAGER_OPERATIONS',
  'STEWARD_NEW_VENTURES',
  'STEWARD_OPERATIONS',
  'DECISION_ISSUER_NEW_VENTURES',
  'DECISION_ISSUER_OPERATIONS',
  'CONTINUATION_REVIEWER_NEW_VENTURES',
  'CONTINUATION_REVIEWER_OPERATIONS',
  'CASE_MANAGER_CS_NEW_VENTURES',
  'CASE_MANAGER_CS_CTS',
  'STEWARD_CS_NEW_VENTURES',
  'STEWARD_CS_CTS',
  'DECISION_ISSUER_CS_NEW_VENTURES',
  'DECISION_ISSUER_CS_CTS'
);
