set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER lms_app WITH PASSWORD 'dev1';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO lms_app;
EOSQL