package uk.co.nstauthority.licensingmanagementservice.hibernate;

import java.util.Objects;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.generator.BeforeExecutionGenerator;
import org.hibernate.generator.EventType;
import org.hibernate.id.IdentityGenerator;

// This is a custom ID generator for Hibernate to allow the creation of entities with a pre-set ID.
// See https://vladmihalcea.com/how-to-combine-the-hibernate-assigned-generator-with-a-sequence-or-an-identity-column/
// https://discourse.hibernate.org/t/hybrid-id-generation-in-hibernate-6-2-is-difficult/7666
public class AssignedIdentityGenerator extends IdentityGenerator implements BeforeExecutionGenerator {

  @Override
  public Object generate(
      SharedSessionContractImplementor session,
      Object entity,
      Object currentValue,
      EventType eventType
  ) {
    return getId(entity, session);
  }

  private static Object getId(
      Object entity,
      SharedSessionContractImplementor session
  ) {
    return session.getEntityPersister(null, entity)
        .getIdentifier(entity, session);
  }

  @Override
  public boolean generatedOnExecution(
      Object entity,
      SharedSessionContractImplementor session
  ) {
    Object id = getId(entity, session);
    return Objects.isNull(id);
  }

  @Override
  public boolean generatedOnExecution() {
    // This method is called to configure a context (using this Generator) without knowledge of a specific Entity.
    // The choice for the real Entity must be made in the this.generatedOnExecution(entity, session) method.
    // For example, find out comment "support mixed-timing generators" in IdentifierGeneratorUtil.class (hibernate-core):
    // true is required, if ID sometimes should be generated by RDBMS (for example by AUTO_INCREMENT)
    return true;
  }
}