spring.datasource.oracle.url: jdbc:oracle:thin:@db-ogadev1.sb2.dev:1521:ogadev1
spring.datasource.oracle.username: GIS_ALPHA
spring.datasource.oracle.password: dev1
spring.datasource.oracle.driver-class-name: oracle.jdbc.OracleDriver
