spring.datasource.oracle.url: ${ORACLE_DB_URL:jdbc:oracle:thin:@db-ogadev1.sb2.dev:1521:ogadev1}
spring.datasource.oracle.username: ${ORACLE_DB_USERNAME:LMS_GIS_MIGRATION}
spring.datasource.oracle.password: ${ORACLE_DB_PASSWORD:dev1}
spring.datasource.oracle.driver-class-name: oracle.jdbc.OracleDriver

spring.jpa.oracle.open-in-view: false
spring.jpa.oracle.properties.hibernate.default_schema: LMS_GIS_MIGRATION
spring.jpa.oracle.properties.hibernate.dialect: org.hibernate.dialect.OracleDialect