spring.application.name: gis-framework

# gRPC client configuration
grpc.client.node-server.address: static://localhost:8082
grpc.client.node-server.negotiation-type: plaintext

# Migration config
gis-framework.migration.ref-block-name-to-license-blocks[16/29][0]=16/29c
gis-framework.migration.ref-block-name-to-license-blocks[16/30][0]=16/29c