spring.application.name: gis-framework

spring.datasource.oracle.url: ${ORACLE_DB_URL:}
spring.datasource.oracle.username: ${ORACLE_DB_USERNAME:}
spring.datasource.oracle.password: ${ORACLE_DB_PASSWORD:}
spring.datasource.oracle.driver-class-name: oracle.jdbc.OracleDriver

spring.jpa.oracle.open-in-view: false
spring.jpa.oracle.properties.hibernate.default_schema: GIS_ALPHA
spring.jpa.oracle.properties.hibernate.dialect: org.hibernate.dialect.OracleDialect

# gRPC client configuration
grpc.client.node-server.address: static://localhost:8082
grpc.client.node-server.negotiation-type: plaintext

# Migration config
gis-framework.migration.ref-block-name-to-license-blocks[16/29][0]=16/29c
gis-framework.migration.ref-block-name-to-license-blocks[16/30][0]=16/29c