package uk.co.nstauthority.licensingmanagementservice.file;

public enum FileUsageType {
  APPLICATION_CONTINUATION_LETTER("APPLICATION-CONTINUATION-LETTER"),
  CONTINUATION_OTHER_REQUIREMENT_DOCUMENT("CONTINUATION-OTHER-REQUIREMENT-DOCUMENT"),
  CONTINUATION_ADDITIONAL_SUPPORTING_DOCUMENT("CONTINUATION-ADDITIONAL-SUPPORTING-DOCUMENT"),
  SCHEDULE_AMENDMENT_APP_SUPPORTING_DOCUMENT("SCHEDULE-AMENDMENT-APP-SUPPORTING-DOCUMENT"),
  FINAL_DECISION_SUPPORT_PAPER("FINAL-DECISION-SUPPORT-PAPER");

  private final String usageType;

  FileUsageType(String usageType) {
    this.usageType = usageType;
  }

  public String getUsageType() {
    return usageType;
  }
}
