set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER xyz_app WITH PASSWORD 'dev1';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO xyz_app;
EOSQL